### ISSUE TITLE
Failed to build DependencyGraph

### ISSUE THREAD

**Issue by zaklampert** [inProgress-team/react-native-mantra-boilerplate#1]
I get the errors

```
Failed to build DependencyGraph: @providesModule naming collision:
  Duplicate module name: validateDOMNesting
```

```
Failed to build DependencyGraph: @providesModule naming collision:
  Duplicate module name: validateDOMNesting
```

```
This error is caused by a @providesModule declaration with the same name accross two different files.
    at HasteMap._updateHasteMap
```

```
Process terminated. Press <enter> to close the window
Failed to build DependencyGraph: @providesModule naming collision:
  Duplicate module name: validateDOMNestinglogout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.
```

after running `react-native run-ios`

**Comment by Mokto** [comment]
Hi,

Thanks for your feedback. I will warn on my README this is alpha release.

I think you used npm@2 to install this, right ?

@jujumoz you got the same error yesterday, right ? How did you manage to make it work ?

**Comment by jusierra** [comment]
Yes, just have to "rm -rf node_modules", switch to node 6, and "npm install" ans it works for me. ;)

**Comment by Mokto** [comment]
I think this is a react-native-router-flux issue. I'll try to fix this if I can.

**Comment by yogiben** [comment]
Getting the same.

Have tried npm install with node versions
- `v5.4.1`
- `v6.2.1`

![image](https://cloud.githubusercontent.com/assets/1703155/16050517/3deed64a-325c-11e6-91b8-1b9ec45402aa.png)

![image](https://cloud.githubusercontent.com/assets/1703155/16050526/485bd7ae-325c-11e6-8f5b-d1a0cc16ba17.png)

**Comment by yogiben** [comment]
@jujumoz can you share which versions of node and npm you're using?

**Comment by jusierra** [comment]
node v6.2.1 & npm v3.9.3 !

**Comment by Mokto** [comment]
I think this is related to npm@2. I'll be looking into this this afternoon.

**Comment by Mokto** [comment]
This is related to https://github.com/aksonov/react-native-router-flux/issues/814

**Comment by Mokto** [comment]
v4.2.1 (npm v2.14.7) : not working.
v6.2.0 (npm v3.8.9) : working.

Make sure you use npm3 ;) It should be working with that.

**Comment by yogiben** [comment]
I misdiagnosed this issue.

https://github.com/inProgress-team/react-native-mantra-boilerplate/pull/3

**Comment by Mokto** [comment]
Ok thanks, I'll close ! ;)
