### ISSUE TITLE
subscription example

### ISSUE THREAD

**Issue by FaridSafi** [inProgress-team/react-native-mantra-boilerplate#5]
Hello, you did an amazing work!
Can you provide an example of subscription please ?

**Comment by Mokto** [comment]
Sure !

In your composer function, you just do 

``` javascript
export const composer({context}, onData) {
   if(Meteor.subscribe('todos').ready()) {
       onData(null, Meteor.collection('todos').find());
   }
}
```

If onData is not called, Loading component is Triggered. See https://github.com/kadirahq/react-komposer
Should work! :)

**Comment by FaridSafi** [comment]
It seems that my app is not yet connected to the DDP server when subscribing in composer, so I am getting `'No subscription existing for'` error

I tried to put the Meteor.subscribe inside a setTimeout() but same results.
I could make it work only by subscribing inside a setTimeout inside the `depsMapper` (which is ugly)

**Comment by jusierra** [comment]
Works perfect for me as @Mokto said (subscribe in composer) ... Your problem must be somewhere else ?

**Comment by Mokto** [comment]
That's weird, because even if you are not connected to DDP server when you subscribe, the subscription is reloaded when you successfully connect.

**Comment by FaridSafi** [comment]
I'm still investigating but what I can say from now is that the first subscription attempt is done without sending authentication to the server (certainly because of the AsyncStorage), then my server returns an error.
I don't have this issue if I subscribe elsewhere than the first screen of my app.

In https://github.com/inProgress-team/react-native-meteor/blob/master/src/Meteor.js#L114

```
      this._loadInitialUser();
      this._subscriptionsRestart();
```

Maybe `this._subscriptionsRestart()` should be executed when `this._loadInitialUser()` is finished ?

**Comment by FaridSafi** [comment]
this commit fixes my issue
https://github.com/FaridSafi/react-native-meteor/commit/933602c2a38fcd2ddbf74fdeab043b3aaa794418

**Comment by FaridSafi** [comment]
I submitted pull request
https://github.com/inProgress-team/react-native-meteor/pull/89

It fixes my issue

**Comment by Mokto** [comment]
1.0.0-rc14. Thanks !
