### ISSUE TITLE
MeteorListView and MeteorComplexListView

### ISSUE THREAD

**Issue by FaridSafi** [inProgress-team/react-native-mantra-boilerplate#6]
Since that the Meteor calls and subscriptions are done in the containers, do you think it's still relevant to use MeteorListView and MeteorComplexListView with this boilerplate ?

**Comment by Mokto** [comment]
Yes I think it works well with React Native Listview component.

Make your subscriptions in your container and use theses components in your views.

**Comment by Mokto** [comment]
BTW I'm going to vacations next 2 weeks but I'm planning to add more relevant code to help new users use this boiler ;)

**Comment by smooJitter** [comment]
What do you mean by relevant?

**Comment by FaridSafi** [comment]
I was wondering if features of MeteorListView/MeteorComplexListView were handled by this boilerplate
